detectors:
  - name: apache_access
    pattern: '^\S+ \S+ \S+ \[[^\]]+\] "\S+ \S+ [^"]+" \d{3} \d+'
    type: apache_access

  - name: syslog
    pattern: '^[A-Z][a-z]{2} \s?\d{1,2} \d{2}:\d{2}:\d{2} .*'
    type: syslog

mappings:
  apache_access:
    fields:
      "@timestamp": ts
      "ecs.version": "8.11.0"
      "event.category": "web"
      "event.kind": "event"
      "http.request.method": http_method
      "url.original": url
      "source.ip": client_ip
      "http.response.status_code": status
      "user_agent.original": user_agent

  syslog:
    fields:
      "@timestamp": ts
      "ecs.version": "8.11.0"
      "event.category": "process"
      "event.kind": "event"
      "host.hostname": host
      "process.name": proc
      "log.level": level
      "message": msg
